CIRCUITPY_WIFI_SSID = "<ssid>"
CIRCUITPY_WIFI_PASSWORD = "<password>"
AIRGRADIENT_IP = "<local airgradient address>"
AIRGRADIENT_ID = "<local airgradient id>"

MQTT_BROKER = "<mqtt broker ip>"
MQTT_USER = "<mqtt broker username>"
MQTT_PASS = "<mqtt broker password>"
